config/routes.rb
AdSpecsRails::Application.routes.draw do
  resources :modals
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :ads
  root to: "ads#index"
  match "/new",     to: "ads#new",                    via: "get"
  # match '/signup',  to: 'users#new',                  via: 'get'
  match '/signin',  to: 'sessions#new',               via: 'get'
  match '/signout', to: 'sessions#destroy',           via: 'delete'
  match "*a",       to: "application#routing_error",  via: 'get'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_protected
	validates :name, presence: true
	validates :category, presence: true
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base

end

app/models/modal.rb
class Modal < ActiveRecord::Base
	attr_protected
	validates :name, presence: true
	validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation, :remember_token
	before_save :create_remember_token
	before_save { self.email = email.downcase }
	validates :name, 	presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i 
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password_confirmation, presence: true
	validates :password, length: { minimum: 6 }
	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  include SessionsHelper
  before_action :signed_in_user
  skip_before_action :signed_in_user, only: [:index, :show]
  def show
    @ad = Ad.find(params[:id])
  end
  def index
    @ads = Ad.all
    respond_to do |format|
      format.html
      format.csv { send_data @ads.to_csv }
      format.xls
      format.json do
        render :json => @ads
      end
      format.pdf do
        render :pdf => "TWPN_Ads"
      end
    end
  end
  def new
    @ad = Ad.new
  end
  def create
    @ad = Ad.create params[:ad]
    if @ad.save
      redirect_to @ad, notice: "Ad successfully created!"
    else
      render 'new' 
    end
  end 
  def edit
    @ad = Ad.find(params[:id])
  end
  def update
    @ad = Ad.find(params[:id])
    if @ad.update_attributes(params[:ad])
      redirect_to @ad, notice: "Ad successfully saved!"
    else
      render 'edit'
    end
  end
  def destroy
    Ad.find(params[:id]).destroy
    redirect_to root_url
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	include SessionsHelper 
	
	def routing_error
	    render "public/404", :status => 404
	end
end

app/controllers/modals_controller.rb
class ModalsController < ApplicationController
	include SessionsHelper
	before_action :signed_in_user
	# GET /modals
	# GET /modals.json
  
	def index
		@modals = Modal.all
	end

	# GET /modals/1
	# GET /modals/1.json
	def show
		@modal = Modal.find(params[:id])
	end

	# GET /modals/new
	def new
		@modal = Modal.new
	end

	# GET /modals/1/edit
	def edit
		@modal = Modal.find(params[:id])
	end

	# POST /modals
	# POST /modals.json
	def create
		@modal = Modal.new(modal_params)
		if @modal.save
			redirect_to @modal, notice: 'New category created! Hot stuff!'
		else
			render action: 'new'
		end
	end

	# PATCH/PUT /modals/1
	# PATCH/PUT /modals/1.json
	def update
		@modal = Modal.find(params[:id])
		if @modal.update_attributes(params[:modal])
			redirect_to root_url, notice: 'Saved! High five!'
		else
			render 'edit'
		end
	end

	# DELETE /modals/1
	# DELETE /modals/1.json
	def destroy
		Modal.find(params[:id]).destroy
		redirect_to root_url
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_modal
		@modal = Modal.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def modal_params
		params.require(:modal).permit(:name, :title, :category, :contents)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
    @modals = Modal.all
	end
	
	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# Sign the user in and redirect to the user's show page.
			sign_in user
			redirect_to root_url
		else
			# Create an error message and re-render the signin form.
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end
	
	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	# GET /users
	# GET /users.json
	def index
		@users = User.all
	end

	# GET /users/1
	# GET /users/1.json
	def show
	end

	# GET /users/new
	def new
		@user = User.new
	end

	# GET /users/1/edit
	def edit
	end

	# POST /users
	# POST /users.json
	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "You're signed in as an Administrator!"
			redirect_to "/"
		else
			render 'new'
		end
	end

	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		respond_to do |format|
			if @user.update(user_params)
				redirect_to @user, notice: 'User was successfully updated.'
			else
				render action: 'edit'
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user.destroy
		respond_to do |format|
			redirect_to users_url
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:user).permit(:name, :email, :password,
		:password_confirmation)
	end
	def signed_in_user
		redirect_to root_url, notice: "Please sign in." unless signed_in?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns...the title.
	def full_title(page_title)
		base_title = "| The Washington Post Company"
		if page_title.empty?
			"Ad Specs #{base_title}"
		else
			"#{page_title} #{base_title}"
		end
	end
	def link_maker(category)
		case category
		when "Standard Ads"
			link_to "Standard Ads", "/#modal-standard", :data => {:toggle => "modal"}
		when "Email"
			link_to "Email", "/#modal-email", :data => {:toggle => "modal"}
		when "Mobile"
			link_to "Mobile", "/#modal-mobile", :data => {:toggle => "modal"}
		when "Video"
			link_to "Video", "/#modal-video", :data => {:toggle => "modal"}
		when "Feature Bars, Tiles & Misc."
			link_to "Feature Bars, Tiles & Misc.", "/#modal-features", :data => {:toggle => "modal"}
		when "Intrusive Ads"
			link_to "Intrusive Ads", "/#modal-intrusive", :data => {:toggle => "modal"}
		else
			category
		end
	end
  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-success"
    else
      flash_type.to_s
    end
  end
end

app/helpers/modals_helper.rb
module ModalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ads/edit.html.erb
<%= provide(:title, "Edit Ad #{@ad.id}")%>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>
      <%= "Edit Listing for Ad #{@ad.id}" %>
    </h1>
    <%= bootstrap_form_for(@ad) do |ad| %>
      <%= ad.alert_message "Please fix the errors below." %>
      <%= ad.text_field :name %>
      <%= ad.select :category, options_for_select([['Standard Ads'],["Feature Bars, Tiles And Misc."],["Intrusive Ads"],['Mobile'],['Email'],['Video']], @ad.category) %>
      <%= ad.text_field :size %>
      <%= ad.text_field :expanded_size %>
      <%= ad.text_field :file_size %>
      <%= ad.text_field :animation, label: "Animation Allowed?" %>
      <%= ad.text_field :third_party, label: "Third Party Tags Accepted?" %>
      <%= ad.text_field :notes %>
      <%= ad.text_field :deadline %>
      <%= ad.text_field :ad_code, label: "Ad Code (optional)" %>
      <span class="help-block">Developers only: insert a TWPN ad <code>div</code> complete with a <code>placeAd2</code> call. This functionality is in beta: please use caution before inserting an ad, as it may blow out of its container on smaller devices.</span>
    <div class="row">
      <div class="col-sm-4">
        <%= link_to "Delete", @ad, method: :delete, data: { confirm: "You sure about that?" }, class: "btn btn-block btn-danger", :role => "button" %>
      </div>
      <div class="col-sm-4">
        <%= link_to "Cancel", @ad, :class => "btn btn-block btn-default", :role => "button" %>
      </div>
      <div class="col-sm-4">
        <%= ad.submit "Save changes", class: "btn btn-block btn-primary", :role => "button" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/ads/index.html.erb
<div class="row">
  <div class="header col-xs-12">
    <h1 id="main_title" class="welcome">Ad Specs: Washington Post Digital</h1>
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <h2>Thank you for your interest in online advertising with Washington Post Digital.  <br />
          Please browse our available ad types, check the guidelines above, or use the search bar below to find exactly what you're looking for.  <br />
          <br />
          All creative tags and accompanying technologies being served by the tags must be SSL Compliant (HTTPS).  Please let us know if this is a problem at all.
        </h2>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="table-container col-md-12 ">
    <table border="0" class="table table-hover table-condensed" id="full_ads_table">
      <thead>
        <th>Name</th>
        <th>Ad Type</th>
        <th>Size (px)</th>
        <th class="hidden-xs">Size Expanded (px)</th>
        <th class="hidden-xs">File Size (Max)</th>
        <th class="hidden-xs">Animation?</th>
        <th class="hidden-xs">Third Party Tags Accepted?</th>
        <th class="hidden-xs">Notes</th>
        <th class="hidden-xs">Submission Deadline</th>
        <% if signed_in? %>
          <th></th>
        <% end %>
      </thead>
      <tbody>
        <% @ads.each do |ad| %>
        <tr id="ad_<%= ad.id %>">
          <td><%= link_to ad.name, ad %></td>
          <td><%= link_maker(ad.category) %></td>
          <td><%= ad.size %></td>
          <td class="hidden-xs"><%= ad.expanded_size %></td>
          <td class="hidden-xs"><%= ad.file_size %></td>
          <td class="hidden-xs"><%= ad.animation %></td>
          <td class="hidden-xs"><%= ad.third_party %></td>
          <td class="hidden-xs"><%= ad.notes %></td>
          <td class="hidden-xs"><%= ad.deadline %></td>
          <% if signed_in? %>
            <td>
              <%= link_to "Show", ad %> <br />
              <%= link_to "Edit", edit_ad_path(ad) %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/ads/index.pdf.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style type="text/css">

    a {color: black;}
    td {border-top: 1px solid black;}
    table {page-break-after:always;} 
    .modal {page-break-after:always;}

    </style>
  </head>
  <body>
    <div id="content">
      <table border="0" class="table table-hover table-bordered table-condensed" id="full_ads_table">
        <thead>
          <th>Sites</th>
          <th>Name</th>
          <th>Ad Type</th>
          <th>Size (px)</th>
          <th>Size Expanded (px)</th>
          <th>File Size (Max)</th>
          <th>Animation?</th>
          <th>Third Party Tags Accepted?</th>
          <th>Notes</th>
          <th>Submission Deadline</th>
        </thead>
        <tbody>
          <% @ads.each do |ad| %>
          <tr id="ad_<%= ad.id %>">
            <td class="sites_column">
              <% if ad.on_post? %>
              <span>WP</span>
              <% end %>
              <% if ad.on_slate? %>
              <span>Slate</span>
              <% end %>
              <% if ad.on_root? %>
              <span>The Root</span>
              <% end %>
            </td>
            <td><%= ad.name %></td>
            <td><%= ad.category %></td>
            <td><%= ad.size %></td>
            <td><%= ad.expanded_size %></td>
            <td><%= ad.file_size %></td>
            <td><%= ad.animation %></td>
            <td><%= ad.third_party %></td>
            <td><%= ad.notes %></td>
            <td><%= ad.deadline %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% @modals.each do |m| %>
    <div id="modal-<%= m.name %>" class="modal">
      <div class="modal-header">
        <h3 id="myModalLabel">
          <%= m.title %>
        </h3>
      </div>
      <div class="modal-body">
        <%= m.contents.html_safe %>
      </div>
    </div>
  <% end %>
    </div>
  </body>
</html>

app/views/ads/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="AdTypes">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">On WP</Data></Cell>
        <Cell><Data ss:Type="String">On Slate</Data></Cell>
        <Cell><Data ss:Type="String">On The Root</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Ad Type</Data></Cell>
        <Cell><Data ss:Type="String">Size (px)</Data></Cell>
        <Cell><Data ss:Type="String">Size Expanded (px)</Data></Cell>
        <Cell><Data ss:Type="String">File Size (Max)</Data></Cell>
        <Cell><Data ss:Type="String">Animation?</Data></Cell>
        <Cell><Data ss:Type="String">Third Party Tags Accepted?</Data></Cell>
        <Cell><Data ss:Type="String">Notes</Data></Cell>
        <Cell><Data ss:Type="String">Submission Deadline</Data></Cell>
      </Row>
    <% @ads.each do |ad| %>
      <Row>
        <Cell><Data ss:Type="String">
          <% if ad.on_post? %>
          Yes
          <% else %> 
          No
          <% end %>
        </Data></Cell>
        <Cell><Data ss:Type="String">
          <% if ad.on_slate? %>
          Yes
          <% else %> 
          No
          <% end %>
        </Data></Cell>
        <Cell><Data ss:Type="String">
          <% if ad.on_root? %>
          Yes
          <% else %> 
          No
          <% end %>
        </Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= link_maker(ad.category) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.size %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.expanded_size %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.file_size %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.animation %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.third_party %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.notes %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ad.deadline %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/ads/show.html.erb
<%= provide(:title, @ad.name ) %>
<%- @modals = Modal.all -%>
<!-- <div class="row"> -->
  <div class="col-sm-4" style="margin-bottom: 15px;">
      <h1>
        <%= @ad.name %>
      </h1>
      <table border="0" class="table table-hover table-condensed">
        <tr>
          <td>
            <strong>Ad Type</strong>
          </td>
          <td>
            <%= link_maker(@ad.category) %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Size (px)</strong>
          </td>
          <td>
            <%= @ad.size %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Size Expanded (px)</strong>
          </td>
          <td>
            <%= @ad.expanded_size %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>File Size (Max)</strong>
          </td>
          <td>
            <%= @ad.file_size %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Animation?</strong>
          </td>
          <td>
            <%= @ad.animation %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Third Party Tags Accepted?</strong>
          </td>
          <td>
            <%= @ad.third_party %>
          </td>
        </tr>
        <td>
          <strong>Submission Deadline</strong>
        </td>
        <td>
          <%= @ad.deadline %>
        </td>
      </tr>
    </table>
    <% if signed_in? %>
      <%= link_to "Edit", edit_ad_path(@ad), :class => "btn btn-info pull-left" %>
    <% end %>
    <%= link_to "Back to Main", root_path, :class => "btn btn-default pull-right" %>
  </div>
  <div class="col-sm-8">
    <div class="demobox">
      <% if @ad.ad_code.present? %>
        <%= render "layouts/adscripts" %>
        <%= @ad.ad_code.html_safe %>
      <% else %>
      <h3>Demo coming soon.</h3>
      <% end %>
    </div>
    
    <% if @ad.notes.present? %>
      <h4>Notes</h4>
      <%= @ad.notes %>
      <hr />
    <% end %>
    
    <% @modals.each do |m| %>
      <% if m.title === @ad.category %>
        <%= m.contents.html_safe %>
        <% if signed_in? %>
          <%= link_to "Edit", edit_modal_path(m), class: "btn btn-info pull-right" %>
        <% end %>
      <% end %>
    <% end %>
    
  </div>
<!-- </div> -->

app/views/layouts/_adscripts.html.erb
<script type="text/javascript" language="Javascript">

var commercialNode = "business";

</script>
<script type="text/javascript" language="Javascript" src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<script type="text/javascript" language="Javascript" src="http://js.washingtonpost.com/wp-srv/ad/generic_ad.js"></script>
<script type="text/javascript" language="Javascript">

wpAd.flags.no_interstitials = true;

</script>
<script type="text/javascript" language="Javascript" src="http://js.washingtonpost.com/wp-srv/ad/wp.js"></script>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 alert <%= bootstrap_class_for(type) %>">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{:role => "navigation"}
  %div.navbar-header
    %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => "#navbar-collapse-container"}}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "http://www.washingtonpost.com", :target => "_blank"}
      %div.post-logo
  %div.collapse.navbar-collapse#navbar-collapse-container
    - if !current_page?(root_path)
      %p.navbar-text.navbar-left.navbar-title-text
        = link_to "Ad Specs", root_path
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{:href => "#", :data => {:toggle => "dropdown"}} 
          Guidelines
          %b.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-third_party"}} Third Party Advertising 
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-terms"}} Terms and Conditions
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-in_house"}} In-House Design Process
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-flash"}} Flash Ads
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-submissions"}} Submissions
      %li.dropdown
        %a.dropdown-toggle{:href => "#", :data => {:toggle => "dropdown"}} 
          Categories
          %b.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-standard"}} Standard Ads
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-features"}} Feature Bars, Tiles & Misc.
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-intrusive"}} Intrusive Ads
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-mobile"}} Mobile
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-email"}} Email
          %li
            %a{:href => "#", :data => {:toggle => "modal", :target => "#modal-video"}} Video
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{:href => "mailto:adspecs@wpost.com"}
          %span.glyphicon.glyphicon-envelope.pull-right.nav-icon
          %span.visible-xs Contact Us
      %li
        %a.dropdown-toggle{ :href => "#",  :data => {:toggle => "dropdown" }}
          %span.glyphicon.glyphicon-cloud-download.pull-right.nav-icon
          %span.visible-xs Export Data
        %ul.dropdown-menu
          %li= link_to "Export as CSV", ads_path(format: "csv")
          %li= link_to "Export as Excel", ads_path(format: "xls")
          %li= link_to "Export as PDF", ads_path(format: "pdf")
      - if signed_in?
        %li.dropdown
          %a.dropdown-toggle{ :href => "#", :data => {:toggle => "dropdown" }} 
            %span.glyphicon.glyphicon-cog.pull-right.nav-icon
            %span.visible-xs Settings
          %ul.dropdown-menu
            %li.current-user-name
              %b= current_user.name
            %li.divider
            %li= link_to "Create New Ad", new_ad_path
            %li= link_to "Sign Out", signout_path, method: "delete"

app/views/layouts/_modals.html.erb
<%- @modals = Modal.all -%>
<% @modals.each do |m| %>
  <div id="modal-<%= m.name %>" class="modal fade modal-<%= m.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 class="modal-title">
            <%= m.title %>
          </h3>
        </div>
        <div class="modal-body">
          <%= m.contents.html_safe %>
        </div>
        <div class="modal-footer" id="footer_<%= m.id %>">
          <% if signed_in? %>
            <%= link_to "Edit", edit_modal_path(m), class: "btn btn-info pull-left", type: "button" %>
          <% end %>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/modals/index.html.haml
%h1 Available Modals

.row
  .col-sm-8.col-sm-offset-2
    %table.table
      %tr
        %th Name
        %th Category
        %th Title
        %th
        %th
        %th
    
      - @modals.each do |modal|
        %tr
          %td= modal.name
          %td= modal.category
          %td= modal.title
          %td= link_to 'Show', modal
          %td= link_to 'Edit', edit_modal_path(modal)
          %td= link_to 'Destroy', modal, :method => :delete, :data => { :confirm => 'Are you sure?' }
    
    %br

    = link_to 'New Modal', new_modal_path, class: "btn btn-primary"

app/views/modals/show.html.haml
=provide(:title, "#{@modal.title}")

.row
  .col-sm-6.col-sm-offset-3
    %h1= "Modal ##{@modal.id}"
    %table.table.table-condensed.table-bordered
      %tr
        %td Name:
        %td= @modal.name
      %tr
        %td Section:
        %td= @modal.category
      %tr
        %td Title:
        %td= @modal.title
      %tr
        %td Contents:
        %td= @modal.contents.html_safe

    = link_to 'Edit', edit_modal_path(@modal), class: "btn pull-right btn-info"
    = link_to 'Back', root_path, class: "btn btn-default pull-left"

app/views/users/_form.html.haml
.row
  .col-sm-6.col-sm-offset-3
    = bootstrap_form_for @user do |f|
      = f.alert_message "Please fix the errors below."
      = f.text_field :name
      = f.text_field :email
      = f.password_field :password
      = f.password_field :password_confirmation
      = link_to 'Back', users_path, class: "btn btn-default pull-left"
      = f.submit "Create my account", class: "btn btn-primary pull-right"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 All Admins

%table.table.table-hover.table-bordered
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/show.html.haml
%p#notice= notice

%p 
  = @user.name
%p
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path